### ISSUE TITLE
Letter Head Logo on PDF

### ISSUE THREAD

**Issue by canlann** [alyf-de/erpnext_druckformate#1]
If we try to get a PDF by pressing:
![image](https://user-images.githubusercontent.com/11473213/100988169-b62ca600-354f-11eb-9072-7aef69e5e188.png)

It doesn't print the company logo:
![image](https://user-images.githubusercontent.com/11473213/100988232-c93f7600-354f-11eb-9ece-3407a099434d.png)

I have tried a workaround to pull the logo from the default company letter head with jinja but yet I haven't found a solution. If done with this fixes URLs in <img src="/files/..." work but <img src="{{ company.company_logo }}"  does not.

Not urgent cause we can "Print" and then save as pdf file in the OS printing menu, but would be nice to have fixed someday.

**Comment by barredterra** [comment]
Did you upload the logo in your Company master? Possibly the file needs to be public.

![company_logo](https://user-images.githubusercontent.com/14891507/101066957-3c200f80-3597-11eb-9f3c-64d06fcfad85.png)

**Comment by canlann** [comment]
Just checked the file, it is public and it is in the company master. What Version of wkhtmltopdf have you installed currently?

**Comment by barredterra** [comment]
`wkhtmltopdf 0.12.5 (with patched qt)`

**Comment by barredterra** [comment]
Maybe a problem with the file format? We're using `.png`, I could imagine that there are problems with `.svg`, for exmaple.

**Comment by barredterra** [comment]
Do you have this problem only with Quotation or with the other formats as well?

Please make sure that the field `company_logo` of you Company master contains something like "/files/YOUR_LOGO.png" and the file really exists at that location.

**Comment by canlann** [comment]
Okay, I have the same version of wkhtmltopdf.
This is from the API representation of the company master, the png file exists.
![image](https://user-images.githubusercontent.com/11473213/101241584-b36cb500-36f7-11eb-95dc-0ef97847f265.png)

To clarify: The logo is shown in the preview, just not in the PDF Version

**Comment by canlann** [comment]
@barredterra 
If you want we can have a look at it on my setup. Write me a PM in discuss.erpnext.com

**Comment by barredterra** [comment]
@canlann please provide detailed instructions how to reproduce the issue on a vanilla ERPNext instance. The company logo get's displayed correctly on all of our deployments.

**Comment by barredterra** [comment]
You could also log into your ERPNext server via SSH and check if you are able to download the logo from there (for example, `wget https://my.erpnext.com/files/logo.png`). Possibly the server cannot find the image at the given location because of some wrong configuration.

**Comment by canlann** [comment]
@barredterra Hey, I did just reset everything and now the logo is being displayed. I don't know what exactly my mistake was.
