### ISSUE TITLE
ERPNext v13 sales_invoice timesheet

### ISSUE THREAD

**Issue by retailify** [alyf-de/erpnext_druckformate#3]
Hello everyone, in ERPNext v13 timesheet.customer_note has to be changed to timesheet.note. I can't say if that changed in v13 since I started working with v13.

**Comment by barredterra** [comment]
Thanks for reporting! I think `timesheet.customer_note ` is actually a custom field in our system,`timesheet.note` would be correct for vanilla systems.

**Comment by barredterra** [comment]
Fixed with ee664d9
