### ISSUE TITLE
Not permitted: insufficient permissions for Dynamic Link

### ISSUE THREAD

**Issue by demetz** [alyf-de/erpnext_druckformate#6]
Hi,

when trying to create a delivery notice, I get a popup with the error:

![grafik](https://user-images.githubusercontent.com/28460533/186364907-36fe033d-7c55-4598-9c8a-58bdc815b5ab.png)

Looking at [delivery_note.html](https://github.com/alyf-de/erpnext_druckformate/blob/44e7c80b94dcc506d170c00c6a75e18b6c5df4b9/print_format/delivery_note.html), I assume the following is causing my issue:
```
{% set company_addresses = frappe.get_list("Dynamic Link", filters={"link_doctype": "Company", "link_name": doc.company, "parenttype": "Address"}, fields=["parent"]) %}
```
The required address information should be available:
![grafik](https://user-images.githubusercontent.com/28460533/186367310-d2699f3a-677b-49a4-8124-c555414329dd.png)

The default delivery notice works fine for me.

**Comment by demetz** [comment]
this seems to be a permission issue related to frappe/erpnext and not the templates...

> frappe.get_list("Dynamic Link", filters={"link_doctype": "Company", "link_name": "othermo", "parenttype": "Address"}, fields=["parent"])

> FrappeException: ["Traceback (most recent call last):\n  File \"apps/frappe/frappe/app.py\", line 69, in application\n    response = frappe.api.handle()\n  File \"apps/frappe/frappe/api.py\", line 127, in handle\n    data = frappe.call(frappe.client.get_list, doctype, **frappe.local.form_dict)\n  File \"apps/frappe/frappe/__init__.py\", line 1599, in call\n    return fn(*args, **newargs)\n  File \"apps/frappe/frappe/client.py\", line 47, in get_list\n    check_parent_permission(parent, doctype)\n  File \"apps/frappe/frappe/model/db_query.py\", line 1001, in check_parent_permission\n    raise frappe.PermissionError\nfrappe.exceptions.PermissionError\n"]

![grafik](https://user-images.githubusercontent.com/28460533/186381152-8a931b77-d5be-4426-beb2-124b71241905.png)

when printing with the admin-user of erpnext, everything works fine... 

however, the user seems to have the right permissions on the company:
![grafik](https://user-images.githubusercontent.com/28460533/186386144-2da8ff32-cc11-495b-8a94-d664a07f7ae6.png)

**Comment by barredterra** [comment]
@demetz thanks for reporting. Please check if #7 solves your problem.

**Comment by demetz** [comment]
Unfortunately, that PR does not solve the issue (I believe you also have to apply it to the header-definition). Even after hardcoding the field `company_address_name`, I still receive the same error...

- using the API directly and replacing all `doc` references with hardcoded values, I can access all data...
- using the admin-account, it also works in the UI; hence, it probably only requires on checkbox in the right place

One small difference I came across: I'm on v14 beta

**Comment by demetz** [comment]
sorry, my bad: the PR works as expected.
